# ============================================================================
# Lesson 17: Swoosh Setup - Email Infrastructure for Phoenix
# ============================================================================
#
# Swoosh is the standard email library for Phoenix applications, providing
# a unified API for sending emails through various delivery services while
# maintaining testability and developer ergonomics.
#
# In this lesson, you'll learn:
# - Installing and configuring Swoosh
# - Understanding adapters for different email providers
# - Setting up development and production mailers
# - Configuring multiple mailers for different purposes
#
# Prerequisites:
# - Phoenix framework basics
# - Understanding of Elixir configuration
# - Familiarity with application supervision trees

# ============================================================================
# Section 1: Introduction to Swoosh
# ============================================================================

defmodule EmailConcepts do
  @moduledoc """
  Swoosh provides a clean abstraction over email delivery, separating:

  1. Email Composition - Building the email structure (to, from, subject, body)
  2. Email Delivery - Actually sending the email through a provider
  3. Email Preview - Viewing emails in development without sending

  This separation allows you to:
  - Write emails once, deliver through any provider
  - Test email content without network calls
  - Preview emails in a browser during development
  - Switch providers without changing application code
  """

  # The basic email structure in Swoosh
  def email_structure_example do
    # Swoosh.Email is a struct containing:
    %Swoosh.Email{
      from: {"Sender Name", "sender@example.com"},
      to: [{"Recipient", "recipient@example.com"}],
      cc: [],
      bcc: [],
      subject: "Email Subject",
      text_body: "Plain text content",
      html_body: "<h1>HTML content</h1>",
      headers: %{},
      attachments: [],
      assigns: %{},        # For template rendering
      provider_options: %{} # Provider-specific options
    }
  end
end

# ============================================================================
# Section 2: Installation and Basic Setup
# ============================================================================

defmodule SwooshInstallation do
  @moduledoc """
  Step-by-step guide to adding Swoosh to your Phoenix application.

  Note: Phoenix 1.6+ includes Swoosh by default. For older projects
  or custom setups, follow these installation steps.
  """

  # Step 1: Add to mix.exs dependencies
  def mix_dependencies do
    """
    # In mix.exs, add these dependencies:

    defp deps do
      [
        # Core Swoosh library
        {:swoosh, "~> 1.16"},

        # For preview in development (included with Phoenix)
        {:phoenix_swoosh, "~> 1.2"},

        # HTTP client for API-based adapters (Mailgun, SendGrid, etc.)
        {:finch, "~> 0.18"},

        # Optional: For Hackney-based adapters
        # {:hackney, "~> 1.20"}
      ]
    end
    """
  end

  # Step 2: Configure the application
  def application_config do
    """
    # In mix.exs, ensure Swoosh is started:

    def application do
      [
        mod: {MyApp.Application, []},
        extra_applications: [:logger, :runtime_tools]
        # Swoosh starts automatically via its application
      ]
    end
    """
  end

  # Step 3: Add Finch to supervision tree
  def supervision_tree_setup do
    """
    # In lib/my_app/application.ex:

    defmodule MyApp.Application do
      use Application

      @impl true
      def start(_type, _args) do
        children = [
          # Start Finch for HTTP requests (used by Swoosh adapters)
          {Finch, name: MyApp.Finch},

          # Other children...
          MyAppWeb.Telemetry,
          MyApp.Repo,
          {Phoenix.PubSub, name: MyApp.PubSub},
          MyAppWeb.Endpoint
        ]

        opts = [strategy: :one_for_one, name: MyApp.Supervisor]
        Supervisor.start_link(children, opts)
      end
    end
    """
  end
end

# ============================================================================
# Section 3: Creating the Mailer Module
# ============================================================================

defmodule MyApp.Mailer do
  @moduledoc """
  The Mailer module is your application's interface to Swoosh.
  It provides the `deliver/1` and `deliver!/1` functions.

  This module is typically generated by Phoenix but can be created manually.
  """

  use Swoosh.Mailer, otp_app: :my_app

  # The `use Swoosh.Mailer` macro provides:
  # - deliver(email) - Returns {:ok, result} or {:error, reason}
  # - deliver!(email) - Returns result or raises on error
  # - deliver_many(emails) - Sends multiple emails
end

# Example of a more sophisticated mailer with custom options
defmodule MyApp.CustomMailer do
  @moduledoc """
  A mailer with custom configuration and helper functions.
  """

  use Swoosh.Mailer, otp_app: :my_app

  alias Swoosh.Email

  @from_address {"MyApp Team", "noreply@myapp.com"}

  @doc """
  Creates a base email with common defaults.
  """
  def base_email do
    Email.new()
    |> Email.from(@from_address)
    |> Email.header("X-Mailer", "MyApp/1.0")
  end

  @doc """
  Delivers an email with automatic error logging.
  """
  def deliver_with_logging(email) do
    case deliver(email) do
      {:ok, result} ->
        # Log successful delivery
        require Logger
        Logger.info("Email delivered to #{inspect(email.to)}")
        {:ok, result}

      {:error, reason} = error ->
        require Logger
        Logger.error("Email delivery failed: #{inspect(reason)}")
        error
    end
  end
end

# ============================================================================
# Section 4: Understanding Adapters
# ============================================================================

defmodule SwooshAdapters do
  @moduledoc """
  Adapters are the bridge between Swoosh and email delivery services.
  Each adapter implements the Swoosh.Adapter behaviour.

  Available adapters:

  DEVELOPMENT/TESTING:
  - Swoosh.Adapters.Local - Stores emails in memory (for dev/preview)
  - Swoosh.Adapters.Test - For ExUnit tests

  SMTP:
  - Swoosh.Adapters.SMTP - Generic SMTP delivery
  - Swoosh.Adapters.AmazonSES - Amazon SES via SMTP

  API-BASED:
  - Swoosh.Adapters.Sendgrid - SendGrid API
  - Swoosh.Adapters.Mailgun - Mailgun API
  - Swoosh.Adapters.Postmark - Postmark API
  - Swoosh.Adapters.Mailjet - Mailjet API
  - Swoosh.Adapters.Sendinblue - Brevo (Sendinblue) API
  - Swoosh.Adapters.SparkPost - SparkPost API
  - Swoosh.Adapters.AmazonSES - Amazon SES API
  """

  # Adapter configuration examples
  def adapter_configs do
    %{
      local: """
        # For development - stores emails in memory
        config :my_app, MyApp.Mailer,
          adapter: Swoosh.Adapters.Local
      """,

      test: """
        # For testing - allows assertions on sent emails
        config :my_app, MyApp.Mailer,
          adapter: Swoosh.Adapters.Test
      """,

      smtp: """
        # Generic SMTP configuration
        config :my_app, MyApp.Mailer,
          adapter: Swoosh.Adapters.SMTP,
          relay: "smtp.example.com",
          port: 587,
          username: "user@example.com",
          password: System.get_env("SMTP_PASSWORD"),
          ssl: false,
          tls: :always,
          auth: :always
      """,

      sendgrid: """
        # SendGrid API
        config :my_app, MyApp.Mailer,
          adapter: Swoosh.Adapters.Sendgrid,
          api_key: System.get_env("SENDGRID_API_KEY")
      """,

      mailgun: """
        # Mailgun API
        config :my_app, MyApp.Mailer,
          adapter: Swoosh.Adapters.Mailgun,
          api_key: System.get_env("MAILGUN_API_KEY"),
          domain: "mail.myapp.com",
          base_url: "https://api.mailgun.net/v3"  # EU: api.eu.mailgun.net
      """,

      postmark: """
        # Postmark API
        config :my_app, MyApp.Mailer,
          adapter: Swoosh.Adapters.Postmark,
          api_key: System.get_env("POSTMARK_API_KEY")
      """,

      amazon_ses: """
        # Amazon SES API
        config :my_app, MyApp.Mailer,
          adapter: Swoosh.Adapters.AmazonSES,
          region: "us-east-1",
          access_key: System.get_env("AWS_ACCESS_KEY_ID"),
          secret: System.get_env("AWS_SECRET_ACCESS_KEY")
      """
    }
  end
end

# ============================================================================
# Section 5: Environment-Specific Configuration
# ============================================================================

defmodule EnvironmentConfig do
  @moduledoc """
  Best practices for configuring Swoosh across different environments.
  """

  # config/config.exs - Shared configuration
  def shared_config do
    """
    # config/config.exs

    # Shared mailer configuration
    config :my_app, MyApp.Mailer,
      # Default from address used application-wide
      default_from: {"MyApp", "noreply@myapp.com"}

    # Configure Swoosh API client (for preview routes in dev)
    config :swoosh, :api_client, false
    """
  end

  # config/dev.exs - Development configuration
  def dev_config do
    """
    # config/dev.exs

    # Use Local adapter - emails stored in memory
    config :my_app, MyApp.Mailer,
      adapter: Swoosh.Adapters.Local

    # Enable Swoosh mailbox preview
    # Emails viewable at /dev/mailbox
    config :swoosh, :api_client, false
    """
  end

  # config/test.exs - Test configuration
  def test_config do
    """
    # config/test.exs

    # Use Test adapter - allows assertions
    config :my_app, MyApp.Mailer,
      adapter: Swoosh.Adapters.Test

    # Disable API client in tests
    config :swoosh, :api_client, false
    """
  end

  # config/runtime.exs - Production configuration
  def runtime_config do
    """
    # config/runtime.exs

    if config_env() == :prod do
      # Determine which adapter to use based on environment variables
      mailer_adapter =
        case System.get_env("MAILER_ADAPTER", "sendgrid") do
          "sendgrid" -> Swoosh.Adapters.Sendgrid
          "mailgun" -> Swoosh.Adapters.Mailgun
          "postmark" -> Swoosh.Adapters.Postmark
          "smtp" -> Swoosh.Adapters.SMTP
          _ -> raise "Unknown MAILER_ADAPTER"
        end

      config :my_app, MyApp.Mailer,
        adapter: mailer_adapter,
        api_key: System.get_env("MAILER_API_KEY") ||
          raise "MAILER_API_KEY environment variable is missing"

      # Enable API client for Swoosh (uses Finch)
      config :swoosh, :api_client, Swoosh.ApiClient.Finch

      # Configure Finch pools for Swoosh
      config :swoosh, :finch_name, MyApp.Finch
    end
    """
  end
end

# ============================================================================
# Section 6: Setting Up the Mailbox Preview (Development)
# ============================================================================

defmodule MailboxPreview do
  @moduledoc """
  The mailbox preview allows you to view sent emails in your browser
  during development without actually sending them.
  """

  # Add to your router
  def router_setup do
    """
    # lib/my_app_web/router.ex

    defmodule MyAppWeb.Router do
      use MyAppWeb, :router

      # ... pipelines ...

      # Development-only routes
      if Mix.env() == :dev do
        # Swoosh mailbox preview
        forward "/mailbox", Plug.Swoosh.MailboxPreview

        # Or with Phoenix.Router scope
        scope "/dev" do
          pipe_through [:browser]

          forward "/mailbox", Plug.Swoosh.MailboxPreview
        end
      end

      # ... other routes ...
    end
    """
  end

  # Alternative: Using Phoenix LiveDashboard integration
  def live_dashboard_integration do
    """
    # In your router, add to LiveDashboard:

    if Mix.env() in [:dev, :test] do
      import Phoenix.LiveDashboard.Router

      scope "/" do
        pipe_through :browser

        live_dashboard "/dashboard",
          metrics: MyAppWeb.Telemetry,
          additional_pages: [
            # Add Swoosh mailbox as a dashboard page
            mailbox: Swoosh.Dashboard
          ]
      end
    end
    """
  end
end

# ============================================================================
# Section 7: Multiple Mailers
# ============================================================================

defmodule MultipleMailers do
  @moduledoc """
  Sometimes you need different mailers for different purposes:
  - Transactional emails (password resets, confirmations)
  - Marketing emails (newsletters, promotions)
  - System notifications (alerts, monitoring)

  Each can use different providers or configurations.
  """
end

# Transactional mailer - high deliverability, fast
defmodule MyApp.TransactionalMailer do
  use Swoosh.Mailer, otp_app: :my_app, mailer: :transactional
end

# Marketing mailer - bulk sending capabilities
defmodule MyApp.MarketingMailer do
  use Swoosh.Mailer, otp_app: :my_app, mailer: :marketing
end

# System mailer - for alerts and monitoring
defmodule MyApp.SystemMailer do
  use Swoosh.Mailer, otp_app: :my_app, mailer: :system
end

defmodule MultipleMailerConfig do
  def configuration do
    """
    # config/runtime.exs

    # Transactional emails via Postmark (high deliverability)
    config :my_app, MyApp.TransactionalMailer,
      adapter: Swoosh.Adapters.Postmark,
      api_key: System.get_env("POSTMARK_API_KEY")

    # Marketing emails via SendGrid (bulk sending)
    config :my_app, MyApp.MarketingMailer,
      adapter: Swoosh.Adapters.Sendgrid,
      api_key: System.get_env("SENDGRID_API_KEY")

    # System alerts via SMTP (internal mail server)
    config :my_app, MyApp.SystemMailer,
      adapter: Swoosh.Adapters.SMTP,
      relay: "internal-smtp.company.com",
      port: 25,
      tls: :never,
      auth: :never
    """
  end
end

# ============================================================================
# Section 8: SMTP Configuration Deep Dive
# ============================================================================

defmodule SMTPConfiguration do
  @moduledoc """
  SMTP adapter configuration options explained.
  """

  def full_smtp_config do
    """
    config :my_app, MyApp.Mailer,
      adapter: Swoosh.Adapters.SMTP,

      # REQUIRED: SMTP server hostname
      relay: "smtp.example.com",

      # Port options:
      # - 25: Standard SMTP (usually blocked by ISPs)
      # - 465: SMTPS (implicit TLS)
      # - 587: Submission (STARTTLS) - RECOMMENDED
      # - 2525: Alternative submission port
      port: 587,

      # Authentication credentials
      username: "user@example.com",
      password: System.get_env("SMTP_PASSWORD"),

      # SSL/TLS options:
      # ssl: true/false - Use implicit TLS (port 465)
      ssl: false,

      # tls: :always/:never/:if_available
      # :always - Require STARTTLS (recommended for port 587)
      # :never - Don't use STARTTLS
      # :if_available - Use if server supports it
      tls: :always,

      # Authentication: :always/:never/:if_available
      auth: :always,

      # Custom TLS options (optional)
      tls_options: [
        verify: :verify_peer,
        cacerts: :certifi.cacerts(),
        depth: 3
      ],

      # Connection timeout in milliseconds
      timeout: 10_000,

      # For debugging - don't use in production
      no_mx_lookups: false,
      retries: 2
    """
  end

  # Common SMTP provider configurations
  def provider_configs do
    %{
      gmail: """
        # Gmail SMTP (requires App Password)
        config :my_app, MyApp.Mailer,
          adapter: Swoosh.Adapters.SMTP,
          relay: "smtp.gmail.com",
          port: 587,
          username: "your-email@gmail.com",
          password: System.get_env("GMAIL_APP_PASSWORD"),
          tls: :always,
          auth: :always
      """,

      outlook: """
        # Microsoft 365 / Outlook
        config :my_app, MyApp.Mailer,
          adapter: Swoosh.Adapters.SMTP,
          relay: "smtp.office365.com",
          port: 587,
          username: "your-email@company.com",
          password: System.get_env("OUTLOOK_PASSWORD"),
          tls: :always,
          auth: :always
      """,

      ses_smtp: """
        # Amazon SES via SMTP
        config :my_app, MyApp.Mailer,
          adapter: Swoosh.Adapters.SMTP,
          relay: "email-smtp.us-east-1.amazonaws.com",
          port: 587,
          username: System.get_env("SES_SMTP_USERNAME"),
          password: System.get_env("SES_SMTP_PASSWORD"),
          tls: :always,
          auth: :always
      """
    }
  end
end

# ============================================================================
# Section 9: Provider-Specific Options
# ============================================================================

defmodule ProviderOptions do
  @moduledoc """
  Each email provider offers unique features accessible through
  provider_options in the Email struct.
  """

  alias Swoosh.Email

  def sendgrid_options do
    Email.new()
    |> Email.from("sender@example.com")
    |> Email.to("recipient@example.com")
    |> Email.subject("With SendGrid Options")
    |> Email.text_body("Hello!")
    |> Email.put_provider_option(:categories, ["welcome", "new_user"])
    |> Email.put_provider_option(:custom_args, %{
      campaign: "onboarding",
      user_id: "12345"
    })
    |> Email.put_provider_option(:send_at, DateTime.to_unix(~U[2024-01-15 09:00:00Z]))
    |> Email.put_provider_option(:tracking_settings, %{
      click_tracking: %{enable: true},
      open_tracking: %{enable: true}
    })
  end

  def mailgun_options do
    Email.new()
    |> Email.from("sender@example.com")
    |> Email.to("recipient@example.com")
    |> Email.subject("With Mailgun Options")
    |> Email.text_body("Hello!")
    |> Email.put_provider_option(:tags, ["welcome", "v2"])
    |> Email.put_provider_option(:tracking, true)
    |> Email.put_provider_option(:tracking_clicks, "htmlonly")
    |> Email.put_provider_option(:tracking_opens, true)
    |> Email.put_provider_option(:variables, %{
      "recipient_name" => "John",
      "account_id" => "12345"
    })
    |> Email.put_provider_option(:delivery_time, "Fri, 15 Jan 2024 09:00:00 GMT")
  end

  def postmark_options do
    Email.new()
    |> Email.from("sender@example.com")
    |> Email.to("recipient@example.com")
    |> Email.subject("With Postmark Options")
    |> Email.text_body("Hello!")
    |> Email.put_provider_option(:tag, "welcome-email")
    |> Email.put_provider_option(:track_opens, true)
    |> Email.put_provider_option(:track_links, "HtmlAndText")
    |> Email.put_provider_option(:message_stream, "outbound")
    |> Email.put_provider_option(:metadata, %{
      "user_id" => "12345",
      "campaign" => "onboarding"
    })
  end

  def amazon_ses_options do
    Email.new()
    |> Email.from("sender@example.com")
    |> Email.to("recipient@example.com")
    |> Email.subject("With SES Options")
    |> Email.text_body("Hello!")
    |> Email.put_provider_option(:configuration_set_name, "my-tracking-config")
    |> Email.put_provider_option(:tags, [
      %{name: "campaign", value: "welcome"},
      %{name: "environment", value: "production"}
    ])
  end
end

# ============================================================================
# Section 10: Practical Examples
# ============================================================================

defmodule MyApp.Emails do
  @moduledoc """
  Example email module demonstrating real-world usage patterns.
  """

  import Swoosh.Email

  @from_address {"MyApp", "noreply@myapp.com"}
  @support_address {"MyApp Support", "support@myapp.com"}

  def welcome_email(user) do
    new()
    |> from(@from_address)
    |> to({user.name, user.email})
    |> subject("Welcome to MyApp!")
    |> text_body("""
    Hi #{user.name},

    Welcome to MyApp! We're excited to have you.

    Get started by visiting: https://myapp.com/getting-started

    Best,
    The MyApp Team
    """)
    |> html_body("""
    <h1>Hi #{user.name}!</h1>
    <p>Welcome to MyApp! We're excited to have you.</p>
    <p><a href="https://myapp.com/getting-started">Get Started</a></p>
    """)
  end

  def password_reset_email(user, reset_token) do
    reset_url = "https://myapp.com/reset-password?token=#{reset_token}"

    new()
    |> from(@from_address)
    |> to({user.name, user.email})
    |> subject("Reset Your Password")
    |> text_body("""
    Hi #{user.name},

    You requested a password reset. Click the link below:

    #{reset_url}

    This link expires in 1 hour.

    If you didn't request this, please ignore this email.
    """)
  end

  def order_confirmation_email(user, order) do
    new()
    |> from(@from_address)
    |> to({user.name, user.email})
    |> subject("Order Confirmation ##{order.number}")
    |> text_body("""
    Thank you for your order!

    Order Number: #{order.number}
    Total: $#{order.total}

    We'll send tracking information when your order ships.
    """)
    |> header("X-Order-ID", to_string(order.id))
  end

  def support_ticket_email(user, ticket) do
    new()
    |> from(@support_address)
    |> to({user.name, user.email})
    |> reply_to(@support_address)
    |> subject("[Ticket ##{ticket.id}] #{ticket.subject}")
    |> text_body("""
    Your support ticket has been created.

    Ticket ID: #{ticket.id}
    Subject: #{ticket.subject}

    Our team will respond within 24 hours.

    Reply to this email to add to your ticket.
    """)
    |> header("X-Ticket-ID", to_string(ticket.id))
  end
end

# ============================================================================
# Section 11: Exercises
# ============================================================================

defmodule Exercises do
  @moduledoc """
  Practice exercises for Swoosh setup and configuration.
  """

  # Exercise 1: Basic Mailer Setup
  # Create a mailer module for a blog application that:
  # - Uses the Local adapter in development
  # - Includes a base_email/0 function with default from address
  # - Has a deliver_later/1 function that logs the email

  # Exercise 2: Multi-Provider Configuration
  # Configure your application to use:
  # - SendGrid for transactional emails
  # - Mailgun for marketing emails
  # - Local adapter in development for both
  # Create separate mailer modules for each purpose

  # Exercise 3: SMTP Debugging
  # Set up SMTP configuration for a Gmail account:
  # - Configure proper TLS settings
  # - Handle connection timeouts
  # - Add error handling and logging

  # Exercise 4: Provider Options
  # Create an email that uses provider-specific options:
  # - Add tracking (opens and clicks)
  # - Schedule delivery for a future time
  # - Add custom metadata/tags

  # Exercise 5: Environment Configuration
  # Create a complete configuration setup that:
  # - Uses Local adapter in dev
  # - Uses Test adapter in test
  # - Reads adapter choice from environment variables in prod
  # - Validates required environment variables at startup
end

# ============================================================================
# Section 12: Solutions
# ============================================================================

defmodule Solutions do
  # Solution 1: Basic Mailer Setup
  defmodule BlogMailer do
    use Swoosh.Mailer, otp_app: :blog

    import Swoosh.Email
    require Logger

    @from {"My Blog", "noreply@myblog.com"}

    def base_email do
      new()
      |> from(@from)
    end

    def deliver_later(email) do
      Logger.info("Queuing email to: #{inspect(email.to)}, subject: #{email.subject}")

      # In a real app, you'd use Oban or similar
      Task.start(fn ->
        case deliver(email) do
          {:ok, _} -> Logger.info("Email delivered successfully")
          {:error, reason} -> Logger.error("Email failed: #{inspect(reason)}")
        end
      end)

      :ok
    end
  end

  # Solution 2 Configuration:
  def multi_provider_config do
    """
    # config/dev.exs
    config :my_app, MyApp.TransactionalMailer,
      adapter: Swoosh.Adapters.Local

    config :my_app, MyApp.MarketingMailer,
      adapter: Swoosh.Adapters.Local

    # config/runtime.exs
    if config_env() == :prod do
      config :my_app, MyApp.TransactionalMailer,
        adapter: Swoosh.Adapters.Sendgrid,
        api_key: System.get_env("SENDGRID_API_KEY")

      config :my_app, MyApp.MarketingMailer,
        adapter: Swoosh.Adapters.Mailgun,
        api_key: System.get_env("MAILGUN_API_KEY"),
        domain: System.get_env("MAILGUN_DOMAIN")
    end
    """
  end

  # Solution 4: Provider Options
  def tracked_email(user) do
    import Swoosh.Email

    Swoosh.Email.new()
    |> from({"MyApp", "noreply@myapp.com"})
    |> to({user.name, user.email})
    |> subject("Your Weekly Summary")
    |> text_body("Here's what happened this week...")
    |> put_provider_option(:tracking_settings, %{
      click_tracking: %{enable: true},
      open_tracking: %{enable: true}
    })
    |> put_provider_option(:send_at, calculate_next_monday_9am())
    |> put_provider_option(:custom_args, %{
      user_id: user.id,
      email_type: "weekly_summary"
    })
  end

  defp calculate_next_monday_9am do
    # Simplified - real implementation would use proper date math
    DateTime.utc_now()
    |> DateTime.add(7 * 24 * 60 * 60, :second)
    |> DateTime.to_unix()
  end
end

# ============================================================================
# Summary
# ============================================================================

defmodule Summary do
  @moduledoc """
  Key takeaways from this lesson:

  1. SWOOSH ARCHITECTURE
     - Separates email composition from delivery
     - Adapters provide provider abstraction
     - Consistent API regardless of provider

  2. CONFIGURATION
     - Use Local adapter in development
     - Use Test adapter for testing
     - Configure production via runtime.exs
     - Support multiple mailers for different purposes

  3. ADAPTERS
     - API-based adapters (SendGrid, Mailgun) require Finch
     - SMTP adapter for direct mail server connection
     - Each adapter has provider-specific options

  4. BEST PRACTICES
     - Never hardcode credentials
     - Use environment variables for sensitive data
     - Configure mailbox preview in development
     - Create base email functions for consistency

  Next lesson: Email Templates - Building beautiful emails with HEEx
  """
end
